<a href="https://colab.research.google.com/github/achuntya/ML-project/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import numpy as np


In [ ]:
arr = np.array([[1,2,4],[7,13,21]])
print(arr)

[[ 1  2  4]
 [ 7 13 21]]


In [ ]:
print("Shape:", arr.shape)

Shape: (2, 3)


In [ ]:
n_rows = 2
n_columns = 3
np.random.rand(n_rows,n_columns)


array([[0.0246973 , 0.18825265, 0.49824341],
       [0.79252054, 0.01256046, 0.75246347]])

In [ ]:
np.zeros((4,5,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [ ]:
np.ones((4,5,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [ ]:
y = np.array([[1, 2, 3],
              [4, 5, 6]])
y_transpose = y.reshape(3,2)
print(y_transpose)

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
y_flat = y.reshape(6,1)

print(y_flat)


[1 2 3 4 5 6]


In [3]:
x = np.array([4,7,11])
y = x.reshape(3,1)
print(y)

[[ 4]
 [ 7]
 [11]]


In [4]:
assert y.shape == (3, 1)

In [5]:
print(y)

[[ 4]
 [ 7]
 [11]]


In [6]:
x = np.array([4, 1, 5, 6, 11])

y = x[1:4:1]


print(y)

z = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

w = z[0:9:2]

print(w)

[1 5 6]
[1 3 5 7 9]


In [14]:
arr_2d = np.array([[4, 5, 2],
          [3, 7, 9],
          [1, 4, 5]])
sliced_arr_2d = np.array([arr_2d[0, 1:3],
                          arr_2d[1, 1:3],
                          arr_2d[2, 1:3]])


print(sliced_arr_2d)


[[5 2]
 [7 9]
 [4 5]]


In [ ]:
arr1 = np.array([1, 2, 3, 4])
b = 1

#
# Implement broadcasting to add b to each element of arr1

#

# print(arr1)

arr2 = np.array([[1, 2, 3],
                 [4, 5, 6]])
arr3 = np.array([[4],
                 [5]])

#
# Multiply each element of the first row of arr2 by 4 and each element of the second row by 5, using only arr2 and arr3

#

print(arr2)
